package com.elmakers.mine.bukkit.persisted;

public class FieldInfo
{
    private boolean auto      = false;

    private boolean contained = false;

    private String  field;

    private String  getter;

    private boolean id        = false;

    private String  name;

    private boolean readonly  = false;

    private String  setter;

    public FieldInfo()
    {
    }

    public FieldInfo(PersistField fieldInfo)
    {
        id = fieldInfo.id();
        auto = fieldInfo.auto();
        contained = fieldInfo.contained();
        readonly = fieldInfo.readonly();
        name = fieldInfo.name();
    }

    public FieldInfo(String name)
    {
        this.name = name;
    }

    public String getField()
    {
        return field;
    }

    public String getGetter()
    {
        return getter;
    }

    public String getName()
    {
        return name;
    }

    public String getSetter()
    {
        return setter;
    }

    public boolean isAutogenerated()
    {
        return auto;
    }

    public boolean isContained()
    {
        return contained;
    }

    public boolean isIdField()
    {
        return id;
    }

    public boolean isReadOnly()
    {
        return readonly;
    }

    public void setAutogenerated(boolean auto)
    {
        this.auto = auto;
    }

    public void setContained(boolean contained)
    {
        this.contained = contained;
    }

    public void setField(String field)
    {
        this.field = field;
    }

    public void setGetter(String getter)
    {
        this.getter = getter;
    }

    public void setIdField(boolean id)
    {
        this.id = id;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public void setReadOnly(boolean readonly)
    {
        this.readonly = readonly;
    }

    public void setSetter(String setter)
    {
        this.setter = setter;
    }
}
